spring:
  application:
    name: Rest Template Client

logging:
  level:
    org.apache.http.impl: debug
    org.apache.http.headers: debug

app:
  user-service:
    url: http://localhost:18000/api/v1/server/users
